FROM ft-rails:on-build

EXPOSE 3000
CMD [ "rails" , "s", "-b", "0.0.0.0", "-p", "3000"]

# How to build it?
# first, build Dockerile image in ft-rails
# docker build -t ex02img /path/to/dockerfile/.

# How to run it?
# docker run --name ex02container -it --rm -p 3000:3000 ex02
